- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install CloudWatch Agent
      get_url:
        url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
        dest: "/tmp/amazon-cloudwatch-agent.deb"

    - name: Install CloudWatch Agent package
      apt:
        deb: "/tmp/amazon-cloudwatch-agent.deb"
        state: present

    # Skip the installation if amazon-ssm-agent is installed by snap
    - name: Check if amazon-ssm-agent is installed by snap
      shell: snap list amazon-ssm-agent
      register: ssm_installed
      ignore_errors: true

    - name: Ensure amazon-ssm-agent is running (if installed by snap)
      systemd:
        name: amazon-ssm-agent
        state: started
        enabled: yes
      when: ssm_installed.rc == 0

    # If amazon-ssm-agent is not installed via snap, install via apt or other method
    - name: Install AWS SSM Agent (if not installed by snap)
      apt:
        name: amazon-ssm-agent
        state: present
      when: ssm_installed.rc != 0

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Git
      apt:
        name: git
        state: present
