---
- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: full

    - name: Install CloudWatch Agent
      get_url:
        url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
        dest: "/tmp/amazon-cloudwatch-agent.deb"
    - name: Install CloudWatch Agent package
      apt:
        deb: "/tmp/amazon-cloudwatch-agent.deb"
        state: present

    - name: Download SSM Agent
      get_url:
        url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
        dest: /tmp/amazon-ssm-agent.deb
      
    - name: Install SSM Agent
      apt:
        deb: /tmp/amazon-ssm-agent.deb
        state: present

    - name: Enable and start AWS SSM Agent
      systemd:
        name: amazon-ssm-agent
        enabled: yes
        state: started

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install additional packages
      apt:
        name:
          - python3-pip
          - unzip
        state: present